version: "3.4"

services:
  frontend:
    build:
      context: CC.Frontend/frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8090:80"
  api:
    build:
      context: .
      dockerfile: CC/Dockerfile
    container_name: controllers
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: db
    ports:
      - "1433:1433"

    environment:
        SA_PASSWORD: "S3cur3P@ssW0rd!"
        ACCEPT_EULA: "Y"