version: "3.4"

services:
  frontend:
    build:
      context: CC.Frontend/frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8090:80"
    network_mode: "host"
  api:
    build:
      context: .
      dockerfile: CC/Dockerfile
    container_name: controllers
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_PORT: 1433
      WAIT_HOSTS: db:1433
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: db
    ports:
      - "1433:1433"
    environment:
      - Database=CCommandContext
      - ACCEPT_EULA=Y